[toolchain]
## working toolchains
# channel = "nightly-2023-12-29"
# channel = "nightly-2024-01-01"
# channel = "nightly-2024-01-04"
# channel = "nightly-2024-01-05"

## bugged toolchains
# channel = "nightly-2024-01-06"
# channel = "nightly-2024-01-07"
# channel = "nightly-2024-01-15"
# channel = "nightly-2024-01-28"
# channel = "nightly-2024-02-15"
# channel = "nightly-2024-03-22"
channel = "nightly"

components = ["rust-src"]
profile = "minimal"
